<a href="https://colab.research.google.com/github/alhasibsifat/Deep-Learning-Basics/blob/main/2.%20Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.5382, -0.2163, -1.2404],
        [ 0.4807, -0.7783,  1.1200]], requires_grad=True)
tensor([-1.4482, -1.4200], requires_grad=True)


In [9]:
def model(x):
  return x @ w.t() + b


In [11]:
pred = model(inputs)
print(pred)

tensor([[-29.9930,  29.6836],
        [-50.8976,  45.5117],
        [-55.5580,   1.0673],
        [ -1.7517,  55.5820],
        [-71.9106,  35.4307]], grad_fn=<AddBackward0>)


In [12]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [16]:
diff = targets - pred
diff_sqr = diff * diff
diff_sqr

tensor([[ 7394.7979,  1625.4156],
        [17396.9727,  3078.9536],
        [30470.4844, 17406.2441],
        [  564.1454,   345.2899],
        [30593.7227,  6983.8315]], grad_fn=<MulBackward0>)

In [17]:
torch.sum(diff_sqr)/diff.numel()

tensor(11585.9863, grad_fn=<DivBackward0>)

In [18]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [33]:
loss = mse(pred,targets)
print(loss)

tensor(11585.9863, grad_fn=<DivBackward0>)


In [35]:
loss.backward()

In [36]:
print(w)
print(w.grad)

tensor([[ 0.5382, -0.2163, -1.2404],
        [ 0.4807, -0.7783,  1.1200]], requires_grad=True)
tensor([[ -9591.6445, -11714.4072,  -7077.2129],
        [ -4668.3213,  -6497.3584,  -3619.8555]])


In [37]:
print(b)
print(b.grad)

tensor([-1.4482, -1.4200], requires_grad=True)
tensor([-118.2222,  -58.5450])


In [38]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [39]:
print(w)
print(b)

tensor([[ 0.6341, -0.0992, -1.1697],
        [ 0.5274, -0.7133,  1.1562]], requires_grad=True)
tensor([-1.4470, -1.4195], requires_grad=True)


In [40]:
pred = model(inputs)
loss = mse(pred,targets)
print(loss)

tensor(8339.0098, grad_fn=<DivBackward0>)


In [43]:
for i in range(10000):
  pred = model(inputs)
  loss = mse(pred, targets)
  loss.backward()
  with torch.no_grad():
     w -= w.grad * 1e-5
     b -= b.grad * 1e-5
     w.grad.zero_()
     b.grad.zero_()


In [44]:
pred = model(inputs)
loss = mse(pred,targets)
print(loss)

tensor(0.4858, grad_fn=<DivBackward0>)


In [45]:
pred

tensor([[ 56.9235,  70.0697],
        [ 82.3583, 100.8207],
        [118.7327, 132.9963],
        [ 21.1120,  37.0452],
        [101.8813, 119.1005]], grad_fn=<AddBackward0>)

In [46]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [47]:
#So dami and gochpada now we got a very accurate model to work!