<a href="https://colab.research.google.com/github/alhasibsifat/Deep-Learning-Basics/blob/main/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t2 = torch.tensor([1.,2,3,4,5])
t2

tensor([1., 2., 3., 4., 5.])

In [ ]:
t3= torch.tensor([[5.,6], [7,8], [9,10],[11,12]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [ ]:
t1.shape

torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4., 5.])


torch.Size([5])

In [ ]:
t3.shape

torch.Size([4, 2])

In [ ]:
x = torch.tensor(4., requires_grad=True)
d = torch.tensor(5., requires_grad=True)
g = torch.tensor(8.)

In [ ]:
c = x + g
c

tensor(12.)

In [ ]:
print(x.grad)

None


In [ ]:
print(d.grad)

None


In [ ]:
a = d*x + g
a

tensor(28.)

In [ ]:
print('da/dx:', x.grad)

da/dx: None


In [ ]:
print('da/dx:', x.grad)

dDD/dx: None


In [ ]:
print(g.grad)

None


In [ ]:
a.backward

<bound method Tensor.backward of tensor(28.)>

In [ ]:
print(x.grad)

None


In [ ]:
print(x.grad)
print(d.grad)
print(g.grad)

None
None
None


In [ ]:
import numpy as np

In [ ]:
x = np.array([[4,5],[6,7],[1,2]])
x

array([[4, 5],
       [6, 7],
       [1, 2]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[4, 5],
        [6, 7],
        [1, 2]])

In [ ]:
z = torch.tensor(x)
z

tensor([[4, 5],
        [6, 7],
        [1, 2]])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
z.dtype

torch.int64

In [ ]:
c = z.numpy()
c

array([[4, 5],
       [6, 7],
       [1, 2]])

In [ ]:
asa = torch.tensor(c)
asa

tensor([[4, 5],
        [6, 7],
        [1, 2]])